# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

author: 技术译民
title: 技术译站
email: ittranslator@163.com
description: >- # this means to ignore newlines until "baseurl:"
  一个技术的“译”站，专注于 IT 技术文章翻译和分享，微信公众号：技术译站
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ittranslator.cn" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  rimland

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
timezone: Asia/Shanghai
minima:
  date_format: "%Y年 %m月 %d日"
  skin: classic

# rss: RSS
google_analytics: UA-169624459-1
lang: zh
future: false
paginate: 10

# Can't access in gfw.
# # Disqus Comments
# disqus:
#   # Leave shortname blank to disable comments site-wide.
#   # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
#   shortname: ittranslator


Navigation:
- title: 一个好用又便宜的V.P`N
  url: https://dash.bitznetuk.com/#/register?code=aqt96fln
- title: JSON 解析
  url: https://h5css.com

header_pages:
#  - tags.html
 - links.md
 - about.markdown
 

jekyll-archives:
  enabled: [year, tags]
  layouts:
    year: year-archive
    tag: tag-archive
  permalinks:
    year: '/year/:year/'
    tag: '/tag/:name/'